### ISSUE TITLE
README is inaccurate

### ISSUE THREAD

**Issue by kenchris** [01org/zephyr.js#694]
There is no ```make dfu-all``` but only a ```make dfu``` now

https://raw.githubusercontent.com/arduino/OpenOCD/master/contrib/99-openocd.rules doesn't exist, it is 60-* something now

**Comment by poussa** [comment]
+1, I noticed the same today.

**Comment by grgustaf** [comment]
This should be fixed in #695, just missed some of these spots in my updates.

**Comment by qiaojingx** [comment]
[README.md](https://github.com/01org/zephyr.js/blob/master/README.md) has been updated with commit [249f119](https://github.com/01org/zephyr.js/commit/249f119cf6f88da5a54d1a6669a59631e0092329) in master.
But broken link still exist in zjs-0.2 branch. Will tracking it in #684

**Comment by poussa** [comment]
We can close this then.
